import Image from "next/image";

export default function Page() {
  return (
    <div style={{ marginTop: "70px", marginBottom: "100px" }}>
      <div
        style={{
          background: "#000",
          width: "100%",
          height: "300px",
          display: "flex",
          justifyContent: "center",
        }}
      >
        <Image
          width={800}
          height={300}
          src={"/images/how-fazesound-works.webp"}
          draggable={false}
        />
      </div>
      <div style={{ display: "flex", justifyContent: "center" }}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            width: "60%",
            marginTop: "25px",
          }}
        >
          <h2 style={{ fontWeight: 700 }}>What is FazeSound</h2>
          <p style={{ marginTop: "8px" }}>
            FazeSound is the first web application that utilizes the latest
            advancements in AI technology to bring high-quality music to its
            audience. The music published on FazeSound is entirely legal and
            meticulously curated, allowing you to access top-notch tracks for
            various projects without the need for payments or attribution. You
            can use these songs as many times as you want in your projects, such
            as:
          </p>
          <ul style={{ marginLeft: "40px" }}>
            <li style={{ marginTop: "8px" }}>YouTube videos</li>
            <li style={{ marginTop: "8px" }}>Video games</li>
            <li style={{ marginTop: "8px" }}>Commercials</li>
            <li style={{ marginTop: "8px" }}>Podcasts</li>
            <li style={{ marginTop: "8px" }}>Animations and cartoons</li>
            <li style={{ marginTop: "8px" }}>Documentaries</li>
            <li style={{ marginTop: "8px" }}>
              Professional or non-professional films/recordings
            </li>
          </ul>
          <p style={{ marginTop: "8px", marginLeft: "40px" }}>
            And many more...
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>Our Objective</h2>
          <p style={{ marginTop: "8px" }}>
            Our goal is to move away from the old ways and the difficulties of
            obtaining high-quality music without legal concerns. Our music is
            completely free from copyrights, and no attribution is required. The
            process of using our tracks is as simple as searching for the songs
            you like and clicking &quot;download.&quot; You can now use the
            music in any project you want, without restrictions or the need for
            attribution.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            No Copyright and No Attribution Required
          </h2>
          <p style={{ marginTop: "8px" }}>
            The main feature that sets FazeSound apart is that no attribution to
            FazeSound is required when using our music in your projects. We want
            to make the use of music as easy as possible and facilitate the
            lives of countless individuals who want to incorporate music into
            their projects but don't know where to obtain it legally.
          </p>
          <p style={{ marginTop: "8px" }}>
            You won't have any copyright issues because our music is 100%
            generated by artificial intelligence. Although AI models are trained
            on existing music data, the generated music is entirely original.
            You can read more about this in our{" "}
            <a
              href="/terms-of-service"
              target="_blank"
              rel="noopener noreferrer"
              style={{ textDecoration: "underline", color: "#2087FF" }}
            >
              Terms of Service
            </a>{" "}
            and{" "}
            <a
              href="/privacy-policy"
              target="_blank"
              rel="noopener noreferrer"
              style={{ textDecoration: "underline", color: "#2087FF" }}
            >
              Privacy Policy
            </a>
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>Licenses</h2>
          <p style={{ marginTop: "8px" }}>
            FazeSound currently operates under a &quot;White License&quot; for
            all songs published on its website, fazesound.com. This license
            permits the unlimited use of music in any project without legal
            issues or attribution requirements.
            <a
              href="/terms-of-service"
              target="_blank"
              rel="noopener noreferrer"
              style={{ textDecoration: "underline", color: "#2087FF" }}
            >
              You can read more about this in the "License" section of our Terms
              of Service.
            </a>
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            FazeSound's Revenue Model
          </h2>
          <p style={{ marginTop: "8px" }}>
            For now, FazeSound will be supported by advertisements. However, our
            revenue model may change in the future. We are working to provide
            the best possible experience, becoming the world's highest-quality
            free music library, and that won't change. In the future, there will
            be many more features that will benefit both users and FazeSound's
            growth.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            Our YouTube Channels
          </h2>
          <p style={{ marginTop: "8px" }}>
            We have dedicated YouTube channels for uploading cinematic and
            electronic music. The cinematic music channel covers a wide range of
            subgenres and types of music, making the uploaded content quite
            varied. You can check it out by clicking{" "}
            <a
              href="https://www.youtube.com/@FazeSound-FreeCinematicMusic?sub_confirmation=1"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "#EE1D52" }}
            >
              here
            </a>
            . We also have an electronic music channel that encompasses the
            subgenres of electronic music and the vast variety of songs within
            this genre. If you'd like to explore our electronic music channel,
            you can click{" "}
            <a
              href="https://www.youtube.com/@FazeSound-FreeElectronic-qv4wo?sub_confirmation=1"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "#EE1D52" }}
            >
              here
            </a>
            .
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>Our Blog</h2>
          <p style={{ marginTop: "8px" }}>
            We understand that selecting music can sometimes be a challenging
            task. That's why we have a blog that will teach you how to use our
            music correctly, using practical examples and songs found on our
            main website, fazesound.com. This way, you can use our tracks
            properly for any project you have in mind.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            The Music of the Future
          </h2>
          <p style={{ marginTop: "8px" }}>
            Our music is entirely generated by state-of-the-art artificial
            intelligence. However, there may be occasional issues due to the
            nature of this technology. Therefore, FazeSound has documentation
            and proof that each song was generated by an AI system without human
            intervention. If there are any legal concerns regarding a particular
            AI-generated song, FazeSound has evidence that the song was
            synthetically generated without manual human input. If you believe
            there is an issue with any of our songs, you can contact us at
            bluefreesounds@gmail.com.
          </p>
        </div>
      </div>
    </div>
  );
}
