export default function Page() {
  return (
    <>
      <div style={{ marginTop: "120px" }}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            width: "60%",
            margin: "auto",
          }}
        >
          <h2 style={{ fontWeight: 700 }}>Terms of Service</h2>
          <p style={{ marginTop: "8px" }}>
            Welcome to FazeSound, a platform that provides free,
            artificially-generated music for personal and commercial use without
            copyright restrictions. These Terms of Service ("Terms") govern your
            use of the website fazesound.com and the services provided through
            it (collectively, the "Services"). By accessing or using the
            Services, you agree to be bound by these Terms.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            1. About the Services
          </h2>
          <p style={{ marginTop: "8px" }}>
            FazeSound is a website operated by FazeSound, which distributes
            innovative music generated using cutting-edge artificial
            intelligence technology. The music available on FazeSound is 100%
            AI-generated by FazeSound using a paid license, and is not subject
            to any copyright or attribution requirements.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            2. License to Use the Services
          </h2>
          <p style={{ marginTop: "8px" }}>
            Subject to your compliance with these Terms, FazeSound grants you a
            limited, non-exclusive, non-transferable, revocable license to
            access and use the Services.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            3. Use of the AI-Generated Music
          </h2>
          <p style={{ marginTop: "8px" }}>
            The AI-generated music available on FazeSound is free for you to
            download, use, modify and reproduce for both personal and commercial
            purposes without any attribution or copyright restrictions. This
            includes using the music in projects like YouTube videos, video
            games, films, and other creative works.
          </p>
          <p style={{ marginTop: "8px" }}>
            FazeSound grants you a perpetual, worldwide, royalty-free license to
            use the AI-generated music, except for reselling or redistributing
            the music as if it were your own original composition. You may not
            claim ownership or authorship of the AI-generated music.
          </p>
          <p style={{ marginTop: "8px" }}>
            The music on FazeSound is 100% artificially generated using advanced
            AI models and does not copy, sample, or replicate any existing
            musical works. However, since AI models are trained on vast
            datasets, there is a possibility that the output may contain some
            similarities or influences from other music in the training data.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            4. Nature of AI-Generated Music
          </h2>
          <p style={{ marginTop: "8px" }}>
            All music on FazeSound is generated by state-of-the-art artificial
            intelligence systems under a paid license owned by FazeSound.
            FazeSound has full documentation and proof that each musical work
            was autonomously created by an AI system without human intervention,
            and does not infringe on any copyrights.
          </p>
          <p style={{ marginTop: "8px" }}>
            While measures are taken to avoid direct copying of existing works,
            the AI generation process is inherently influenced by the data it
            was trained on. As such, the AI-generated music may exhibit certain
            commonalities, patterns, or inspirations derived from its training
            data, which includes a vast collection of music across genres and
            eras.
          </p>
          <p style={{ marginTop: "8px" }}>
            By using the Services, you acknowledge and agree that FazeSound
            shall not be liable for any perceived or inadvertent similarities
            between the AI-generated music and other works. These similarities
            are an expected byproduct of the innovative AI technology employed,
            and do not constitute copyright infringement.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            5. Prohibited Conduct
          </h2>
          <p style={{ marginTop: "8px" }}>
            You agree not to use the Services or the AI-generated music in any
            way that:
          </p>
          <ul style={{ marginLeft: "40px" }}>
            <li style={{ marginTop: "8px" }}>
              Violates any applicable laws or regulations
            </li>
            <li style={{ marginTop: "8px" }}>
              Infringes on the rights of others, including intellectual property
              rights
            </li>
            <li style={{ marginTop: "8px" }}>
              Is harmful, threatening, abusive, harassing, defamatory, or
              obscene
            </li>
            <li style={{ marginTop: "8px" }}>
              Attempts to gain unauthorized access to the Services or other
              systems
            </li>
            <li style={{ marginTop: "8px" }}>
              Resells or redistributes the AI-generated music as your own
              original composition
            </li>
          </ul>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            6. Intellectual Property
          </h2>
          <p style={{ marginTop: "8px" }}>
            All content on FazeSound, including the AI-generated music, is owned
            by FazeSound. You acknowledge that the Services are protected by
            intellectual property laws and that you do not acquire any ownership
            rights in the Services or the music.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            7. Disclaimer of Warranties
          </h2>
          <p style={{ marginTop: "8px" }}>
            The Services and the AI-generated music are provided "as is" and "as
            available" without warranties of any kind, express or implied,
            including but not limited to warranties of merchantability, fitness
            for a particular purpose, and non-infringement.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            8. Limitation of Liability
          </h2>
          <p style={{ marginTop: "8px" }}>
            In no event shall FazeSound or its affiliates be liable for any
            indirect, incidental, special, consequential, or punitive damages
            arising out of or related to your use of the Services or the
            AI-generated music.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>9. License</h2>{" "}
          <p style={{ marginTop: "8px" }}>
            {" "}
            All music published on FazeSound.com is licensed under the "White
            License," which grants broad rights for the use, modification, and
            distribution of the AI-generated musical works, both for commercial
            and non-commercial purposes, solely for your own projects.{" "}
          </p>{" "}
          <p style={{ marginTop: "8px" }}>
            {" "}
            Under the White License, you are granted a worldwide, non-exclusive,
            royalty-free, perpetual, and irrevocable license to exercise the
            following rights over the AI-generated music:{" "}
          </p>{" "}
          <ul style={{ marginLeft: "40px" }}>
            {" "}
            <li style={{ marginTop: "8px" }}>
              {" "}
              Use, reproduce, modify, prepare derivative works of, publicly
              display, publicly perform, and distribute the AI-generated music,
              in whole or in part, for any purpose, including commercial
              projects of your own.{" "}
            </li>{" "}
          </ul>{" "}
          <p style={{ marginTop: "8px" }}>
            {" "}
            However, you are not permitted to resell or sublicense the
            AI-generated music to third parties. The White License grants you
            the rights to use the music solely for your own projects and not for
            redistribution or licensing to others.{" "}
          </p>{" "}
          <p style={{ marginTop: "8px" }}>
            {" "}
            The White License effectively places the AI-generated music in the
            public domain for your own use, allowing for unrestricted use,
            modification, and distribution in your projects, subject only to the
            restrictions outlined in these Terms of Service, including the
            prohibition on reselling or sublicensing the music.{" "}
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            10. Modifications
          </h2>
          <p style={{ marginTop: "8px" }}>
            FazeSound reserves the right to modify or discontinue the Services
            or these Terms at any time without notice.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>
            11. Governing Law
          </h2>
          <p style={{ marginTop: "8px" }}>
            These Terms shall be governed by and construed in accordance with
            the laws of Colombia, without regard to its conflict of laws
            principles.
          </p>
          <h2 style={{ fontWeight: 700, marginTop: "8px" }}>12. Contact Us</h2>
          <p style={{ marginTop: "8px" }}>
            If you have any questions or concerns about these Terms, the AI
            generation process, or the groundbreaking AI-generated music on the
            Services, please contact us at bluefreesounds@gmail.com.
          </p>
          <p style={{ marginTop: "8px" }}>
            By continuing to use the Services, you acknowledge that you have
            read, understood, and agreed to be bound by these Terms of Service.
          </p>
        </div>
      </div>
      <div style={{ height: "100px" }}></div>
    </>
  );
}
